### ISSUE TITLE
提案: man コマンドの説明をなくす

### ISSUE THREAD

**Issue by hir0mi** [hiroponz/tutorial-linux-command-line-beginner#1]
### 提案内容

今回のチュートリアルでは、man コマンドにまで踏み込まなくても良さそう

このチュートリアルの実施が必要な人が各コマンドの意味を知りたければ、google 検索してもらった方が良いと思う

**Comment by hiroponz** [comment]
確かに、必要最低限にした法がよいですね。削りましょう。
